### ISSUE TITLE
org.freedesktop.Platform 23.08

### ISSUE THREAD

**Issue by tim77** [flathub/io.github.kotatogram#49]
Kotatogram currently built upon `org.freedesktop.Platform-21.08` which reach end of life soon. Please update to new runtime.

**Comment by ilya-fedin** [comment]
I'm not sure that's realistic... We're blocked on old webrtc not being able to build (or builds but doesn't actually work, don't remember exactly, maybe both) with newer runtimes and webrtc doesn't have stable API, so in order to use newer webrtc, kotatogram has to be rebased on newer tdesktop (or someone has to manually update the related to code to newer webrtc APIs) and sadly the main developer (@EricKotato) has no spare time AFAIK.
